# Generated by Django 3.1 on 2024-03-22 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galtwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='last_active',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
