# Generated by Django 3.1 on 2024-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galtwo', '0002_auto_20240322_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='current_population',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planets',
            name='max_population',
            field=models.BigIntegerField(default=0),
        ),
    ]
