# Generated by Django 3.1 on 2024-05-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galtwo', '0004_sensing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='color_settings',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('O', 'Orange'), ('Y', 'Yellow'), ('I', 'Indigo'), ('V', 'Violet'), ('W', 'White'), ('P', 'Pink'), ('N', 'Brown'), ('C', 'Cyan'), ('A', 'Navy')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='map_setting',
            field=models.CharField(choices=[('UE', 'Unexplored planets'), ('PE', 'Planets of empire'), ('PF', 'Planets of faction '), ('YE', 'Your empire'), ('YR', 'Your portals'), ('YP', 'Your planets'), ('SC', 'Scouted Planets'), ('SS', 'Sensed Systems')], default='UE', max_length=2),
        ),
    ]
