# Generated by Django 3.1 on 2024-11-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galtwo', '0005_auto_20240504_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouting',
            name='empire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galtwo.empire'),
        ),
    ]
