# Generated by Django 3.1 on 2024-11-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galtwo', '0006_scouting_empire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticks_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('calc_time_ms', models.DecimalField(decimal_places=6, max_digits=12)),
                ('dt', models.DateTimeField()),
            ],
        ),
    ]
