# Generated by Django 3.1 on 2024-12-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galtwo', '0008_ticks_log_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundstatus',
            name='tick_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('SA', 'Successfull Attack'), ('UA', 'Unsuccessfull Attack'), ('SD', 'Successfull Defence'), ('UD', 'Unsuccessfull Defence'), ('SE', 'Successfull Exploration'), ('UE', 'Unsuccessfull Exploration'), ('PA', 'Psychic Attack'), ('PD', 'Psychic Defence'), ('AA', 'Agent Attack'), ('AD', 'Agent Defence'), ('GA', 'Ghost Attack'), ('GD', 'Ghost Defence'), ('SI', 'Sent aid'), ('RA', 'Requested aid'), ('M', 'Market operation'), ('N', 'None'), ('BB', 'Buildings Built'), ('UB', 'Units Built'), ('MS', 'Message Sent'), ('MR', 'Message Received'), ('RWD', 'Relation War Declared'), ('RWE', 'Relation War Ended'), ('RNP', 'Relation Nap Proposed'), ('RND', 'Relation Nap Declared'), ('RNE', 'Relation Nap Ended'), ('RAP', 'Relation Alliance Proposed'), ('RAD', 'Relation Alliance Declared'), ('RAE', 'Relation Alliance Ended'), ('FS', 'Fleet Stationed'), ('FU', 'Fleet Station Unsuccessful'), ('FM', 'Fleet Merged'), ('FJ', 'Fleet Joined Main'), ('E', 'Something Extra'), ('RCP', 'Ceasefire Proposed'), ('RCD', 'Ceasefire Declared'), ('DU', 'Flying Dutchman'), ('TE', 'Terraformer')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='relations',
            name='relation_type',
            field=models.CharField(choices=[('AO', 'Alliance offered'), ('W', 'War declared'), ('A', 'Alliance'), ('NO', 'Non agression pact offered'), ('NC', 'Non agression pact cancelled'), ('PC', 'Permanent non agression pact cancelled'), ('N', 'Non agression pact'), ('C', 'Ceasefire'), ('CO', 'Ceasefire offered')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='race',
            field=models.CharField(blank=True, choices=[('HK', 'Harks'), ('MT', 'Manticarias'), ('FH', 'Foohons'), ('SB', 'Spacebornes'), ('DW', 'Dreamweavers'), ('WK', 'Wookiees')], default=None, max_length=2, null=True),
        ),
    ]
