# Generated by Django 3.1 on 2025-01-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galtwo', '0009_auto_20241219_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specop_type', models.CharField(choices=[('O', 'Agent operation'), ('S', 'Psychic spell'), ('G', 'Ghost incantation')], default='O', max_length=1)),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ident', models.CharField(max_length=2)),
                ('tech', models.IntegerField()),
                ('readiness', models.IntegerField()),
                ('difficulty', models.DecimalField(decimal_places=1, max_digits=2)),
                ('selfsp', models.BooleanField(default=False)),
                ('stealth', models.BooleanField(default=False)),
                ('description', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='fleet',
            name='random',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='roundstatus',
            name='emphold',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galtwo.empire'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('SA', 'Successfull Attack'), ('UA', 'Unsuccessfull Attack'), ('SD', 'Successfull Defence'), ('UD', 'Unsuccessfull Defence'), ('SE', 'Successfull Exploration'), ('UE', 'Unsuccessfull Exploration'), ('PA', 'Psychic Attack'), ('PD', 'Psychic Defence'), ('AA', 'Agent Attack'), ('AD', 'Agent Defence'), ('GA', 'Ghost Attack'), ('GD', 'Ghost Defence'), ('SI', 'Sent aid'), ('RA', 'Requested aid'), ('M', 'Market operation'), ('N', 'None'), ('BB', 'Buildings Built'), ('UB', 'Units Built'), ('MS', 'Message Sent'), ('MR', 'Message Received'), ('RWD', 'Relation War Declared'), ('RWE', 'Relation War Ended'), ('RNP', 'Relation Nap Proposed'), ('RND', 'Relation Nap Declared'), ('RNE', 'Relation Nap Ended'), ('RAP', 'Relation Alliance Proposed'), ('RAD', 'Relation Alliance Declared'), ('RAE', 'Relation Alliance Ended'), ('FS', 'Fleet Stationed'), ('FU', 'Fleet Station Unsuccessful'), ('FM', 'Fleet Merged'), ('FJ', 'Fleet Joined Main'), ('E', 'Something Extra'), ('RCP', 'Ceasefire Proposed'), ('RCD', 'Ceasefire Declared'), ('DU', 'Flying Dutchman'), ('TE', 'Terraformer'), ('SK', 'Skrull')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='race',
            field=models.CharField(blank=True, choices=[('HK', 'Harks'), ('MT', 'Manticarias'), ('FH', 'Foohons'), ('SB', 'Spacebornes'), ('DW', 'Dreamweavers'), ('WK', 'Wookiees'), ('FT', 'Furtifons'), ('SM', 'Samsonites')], default=None, max_length=2, null=True),
        ),
    ]
