# Generated by Django 3.1 on 2024-02-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_scouting_empire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scouting',
            name='empire',
        ),
    ]
