# Generated by Django 3.1 on 2024-02-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_scouting_empire'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouting',
            name='empire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empire'),
        ),
    ]
