# Generated by Django 3.1 on 2024-03-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_scouting_empire'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='last_active',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
