# Generated by Django 3.1 on 2024-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20240322_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='color_settings',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('O', 'Orange'), ('Y', 'Yellow'), ('I', 'Indigo'), ('V', 'Violet'), ('W', 'White'), ('P', 'Pink'), ('N', 'Brown'), ('C', 'Cyan')], default='G', max_length=1),
        ),
    ]
