# Generated by Django 3.1 on 2024-11-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_ticks_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticks_log',
            name='error',
            field=models.TextField(null=True),
        ),
    ]
