# Generated by Django 3.1 on 2025-01-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_planet_system_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='system_id',
            new_name='system',
        ),
    ]
